### ISSUE TITLE
`safeNestTransfer` is redundant

### ISSUE THREAD

**Issue by Ayuilos** [rmrk-team/evm#52]
https://github.com/rmrk-team/evm/blob/d921674ddd3b9b751f549f6efb8d08d1eb86d409/contracts/RMRK/RMRKNesting.sol#L292

The "safe" function is for preventing token wrongly sending to a common contract, the `_nestTransfer` has already been seen as one Nesting token be sent to another Nesting contract, it did contract interface check in internal code.

I think it's better to define a `safeTransferNestingFrom` function as I defined in PR before.
`safeTransferFrom` means "I wanna safe sending the token as a ERC721 to a common contract".
`safeTransferNestingFrom` means "I wanna safe sending the token as a Nesting to a common contract".

**Comment by Ayuilos** [comment]
So does here: https://github.com/rmrk-team/evm/blob/63059a4ef32b90829b86d9944f82f48dbeb59d74/contracts/RMRK/RMRKNesting.sol#L158

**Comment by steven2308** [comment]
Inner functions `_nestMint` and `_nestTransfer` do check for the interface because we need to call `addChild` on the destination. I think we agree until here.
Quoting from OZ docs just for context:
> [IERC721Receiver](https://docs.openzeppelin.com/contracts/3.x/api/token/erc721#IERC721Receiver) can be used to prevent tokens from becoming forever locked in contracts. Imagine sending an in-game item to an exchange address that can’t send it back!. When using [safeTransferFrom](https://docs.openzeppelin.com/contracts/3.x/api/token/erc721#IERC721-safeTransferFrom), the token contract checks to see that the receiver is an [IERC721Receiver](https://docs.openzeppelin.com/contracts/3.x/api/token/erc721#IERC721Receiver), which implies that it knows how to handle [ERC721](https://docs.openzeppelin.com/contracts/3.x/api/token/erc721#ERC721) tokens

If we're using either `nestMint` or `nestTransfer`, the receiver cannot simply implement `IRMRKNestingReceiver`, it has to implement `IRMRKNesting` or the `addChild` call will fail. So I agree it makes no sense to have this `safeNestMint` and `safeNestTransfer`. I will remove those.

Now, if we want to have an equivalent functionality as `IERC721Receiver`, I wonder if we shall
1. Allow implementers of `IERC721Receiver` receive our NFTs.
2. Force them to implement `IRMRKNestingReceiver`
3. Allow both.

What do you think @Ayuilos  @CicadaNCR  @stevyhacker

**Comment by Ayuilos** [comment]
I think it's totally acceptable that the receiver contract just implement `IERC721Receiver` because Nesting is fully compatible with ERC721, it's just a downgrade action.
ERC721 is similar to a pocket that just needs to hold things, while Nesting is a waterproof pocket.
The "safe" starts from the point of view of the sender, so for sender, he/she will have 2 options:
- send it as a ERC721, the target contract needs to support `IERC721`
- send it as a Nesting, the target contract needs to support both `IERC721` and `IRMRKNesting`

**Comment by stevyhacker** [comment]
> 1. Allow implementers of IERC721Receiver receive our NFTs.
> 2. Force them to implement IRMRKNestingReceiver
> 3. Allow both.

I think the first point makes sense, if we want to have ERC721 compatibility we should allow transferring to `IERC721Receiver`. Regarding nestTransfer check for `IRMRKNestingReceiver` interface implementation is enforced already.

**Comment by steven2308** [comment]
I agree, just a clarification: We currently check for `IRMRKNesting` support since it's what we need.  `IRMRKNestingReceiver` is completely unnecessary so I'll just remove it. I have all the changes in a PR, will push soon.

**Comment by steven2308** [comment]
PR [Here](https://github.com/rmrk-team/evm/pull/53)
